

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_KEYWORD = "ADD_KEYWORD";
export const RESET_CATEGORY = "RESET_CATEGORY";
export const SET_USEREMAIL = "SET_USEREMAIL";
export const SET_ACCOUNTSTATE = "SET_ACCOUNTSTATE";
