name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
      - production

jobs:
  block_release_if_hot_fixing:
    runs-on: ubuntu-latest
    name: Cancel the staging build
    steps:
      - name: Cancel workflow if PR is named cancel-build
        id: cancelBuild
        uses: yolanlepibrac/block-deployment@v1.11
        with:
          pr-name: 'cancel-build'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output cancel_build
        run: echo "The build need to be cancel - ${{ steps.cancelBuild.outputs.cancel_build }}"