name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
      - production

jobs:
  cancel_build_when_hot_fixing:
    runs-on: ubuntu-latest
    outputs:
      cancel_build: ${{ steps.cancel_build_when_hot_fixing.outputs.cancel_build }}
    steps:
      - name: Cancel workflow if PR is named cancel-build
        id: cancelBuild
        uses: yolanlepibrac/block-deployment@v2.1
        with:
          pr-name: 'cancel-build'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  log_something:
    runs-on: ubuntu-latest
    needs: [cancel_build_when_hot_fixing]
    if:  ${{ needs.block_release_if_hot_fixing.outputs.cancel_build != 'true' }}
    steps:
      - name: the rest jobs
        run: echo "run the rest jobs"