name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
      - production

jobs:
  block_release_if_hot_fixing:
    runs-on: ubuntu-latest
    name: Cancel the staging build
    outputs:
      cancel_build: ${{ steps.cancelBuild.outputs.cancel_build }}
    steps:
      - name: Cancel workflow if PR is named cancel-build
        id: cancelBuild
        uses: yolanlepibrac/block-deployment@v1.11
        with:
          pr-name: 'cancel-build'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  log_something:
    runs-on: ubuntu-latest
    needs: [block_release_if_hot_fixing]
    if: needs.block_release_if_hot_fixing.outputs.cancel_build == 'false'
    steps:
      - name: the rest jobs
        run: echo "run the rest jobs"